##########################
#  Archivo para usar en portainer 
# 1. Crear las imagenes. Comprimiendo frontnd y subiendolo
# 2. Crear api, comprimiendo toda la carpeta externa y eliminando los archivos y/o carpetas que no se necesitan.
##########################

version: '3.8'
services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: helix-web
    image: helix:web
    restart: always
    ports:
      - "9091:80"
    
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: helix-api
    image: helix:api
    restart: always
    ports:
      - "9090:5000"
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}